### ISSUE TITLE
Vectoroscope for DD-Analyse

### ISSUE THREAD

**Issue by Zcooger** [happycube/ld-decode#568] opened 2020-11-23 17:29 UTC
Hello. This ticket is intended to suggest adding a vector display as an alternative to a waveform monitor in the GUI.

**Comment by atsampson** [comment] 2020-11-23 18:56
This idea's been mentioned in #305, which also has some description of what would be necessary to support it.

**Comment by simoninns** [comment] 2020-11-29 08:04
Closing as duplicate of #305

**Closed by simoninns** 2020-11-29 08:04 UTC
