### ISSUE TITLE
Please implement "disc flip."

### ISSUE THREAD

**Issue by toynbeeidea** [happycube/ld-decode#178] opened 2019-04-04 05:22 UTC
I recently captured a two-sided disc.  With my more "conventional" capture setup, this is no issue - screen is displayed showing a disc-flip is in progress, which I can then slice out of my final project.  Not so with the DDD, it seems.  ld-decode stopped at the end of side 1 with a "lead out" frame at 59847.  But the data during the flip crashes with all sorts of errors - I had to manually seek to 60096 to proceed with the next side.  I guess this is similar to the "late spinup" issue (#172).

**Comment by Gamnn** [comment] 2019-04-09 08:54
duplicate of #40.

**Closed** 2019-04-09 16:10 UTC
